image: Visual Studio 2019

shallow_clone: true

test:
  assemblies:
    only:
      - Rebus.AmazonS3.Tests.dll

cache:
  - packages -> **\packages.config
  - '%LocalAppData%\NuGet\Cache'

before_build:
  - appveyor-retry dotnet restore -v Minimal

build_script:
  - dotnet build Rebus.AmazonS3 -c Release 
  - dotnet build Rebus.AmazonS3.Tests -c Release 
